# site settings
title: Pepper Wang
subtitle: 
email: xiaoning.wang@mail.mcgill.ca
description: My design, my works, my life.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Pepper Wang
street_address: 
city: Montreal
state: Quebec
zip_code: 
country: Canada
phone: (437)-985-1603

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram: https://www.instagram.com/elopewithpepper/
  LinkedIn: https://www.linkedin.com/in/xiaoning-wang-aa47261b5/
  Twitter: 
  Facebook:
  Slack: 

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
